### ISSUE TITLE
支持正义查重

### ISSUE THREAD

**Issue by yllhwa** [stream2000/ASoulCnki#1]
有什么需求吗，我也想帮忙捏![](https://ftp.bmp.ovh/imgs/2021/06/43d9dfd2b91597d1.png)

**Comment by stream2000** [comment]
可以啊，欢迎来玩（ '▿ ' ）包括你就三个人了，要不要拉个小团体👀

**Comment by yllhwa** [comment]
小团体发展成大集体😀
我的邮箱是yll2002mail#gmail.com
