### ISSUE TITLE
不知道是不是bug

### ISSUE THREAD

**Issue by kpgong** [stream2000/ASoulCnki#12]
查 `好得太假了。假得一眼真。` 会返回结果 `复制比：0%`。
但是，如果查 `好得太假了；假得一眼真；` 或者 `好得太假了。（换行）假得一眼真。` 就返回结果 `复制比：100%`。

原文是
```plain
然然不是坏女人。
然然是绝世好女人。
好得太假了。
假得一眼真。
真得像是喝醉了的人看星星。
烛光晚餐，玫瑰花瓣，红酒杯。
视野里一切都变美。
```

我开始以为是它对换行超级敏感，但是 `好得太假了；假得一眼真；` 没有换行、符号也不对，却能查到原文……

然然，你带我走吧😭😭😭

**Comment by yllhwa** [comment]
应该是对短文本超级敏感。短文本会找到无关的文本，经过修正算法后就变成0％了。
顺便提一嘴，敏感点是连续四个字相同😈

**Comment by kpgong** [comment]
> 应该是对短文本超级敏感。短文本会找到无关的文本，经过修正算法后就变成0％了。
> 顺便提一嘴，敏感点是连续四个字相同😈

好的捏。所以提交的文本太短算是“用错了”。

然然，我带你走吧😭😭😭
