### ISSUE TITLE
是否考虑开发api接口？

### ISSUE THREAD

**Issue by Suika99** [stream2000/ASoulCnki#16]
开发者大佬你好，我是qq机器人相关的开发者，也是嘉心糖
之前也在机器人做了一些asoul账号粉丝数据，查某用户成分（共同关注）等功能

请问该项目是否有打算开发开放api的计划呢？ 想给我的机器人接入直接在q群里就能查重捏~

**Comment by stream2000** [comment]
预计会产生多大的负载呢？ 如果不大的话一般没什么问题的，我们目前也没有怎么做限制，api.md 里有请求的方法。 未来如果爬虫类的请求产生比较大负载影响线上服务的时候才会去做一些措施来限制访问。
