### ISSUE TITLE
建议改为“除本人言论外复制比”

### ISSUE THREAD

**Issue by hpbtql** [stream2000/ASoulCnki#18]
如在[这条动态](https://t.bilibili.com/542063450157261480?tab=2)下此条
> 鼠鼠一回到宿舍，所有人便都看着他笑，有的叫道，“嘉心糖，你的然然捏？”鼠鼠不回答，掏出了手机，“嘉然小姐带我走吧。”打开bilibili嘉然今天吃什么。
> 他们又故意的高声嚷道，
> “嘉心糖发病了！”鼠鼠睁大眼睛说，“我没病……”
> “什么没病？天天看着你的夹子音纸片人。
> ”鼠鼠便涨红了脸，额上的青筋条条绽出，争辩道，“嘉然小姐才不是纸片人捏……夹子音……嘉然小姐是天使”接连便是难懂的话，什么“可是她喜欢猫”，“天国的锦缎”之类，引得众人都哄笑起来：宿舍外充满了快活的空气。

进行查重后提示总文字复制比为99.58%，溯源显示其与[此链接](https://t.bilibili.com/541668124183422463/#reply4813843230)内容重复，此条即为原作者所发，不应判为重复。

望优化！

**Comment by stream2000** [comment]
这个我们也考虑过，所以把复制后的评价改成了“请根据实际情况判断”。实现这个本身不是很难，但是对于用户来说可能需要在查重的时候多填写一次用户名。 现在查重的复制结果里已经会显示原作者了，根据我的观察大家都不会误判是否为原创/原偷？ 所以我现在感觉还是保持现有的设计比较好， 我们之后的努力方向会往优化原作者选取方面走。 感谢你的反馈捏， 如果还有什么我没考虑到的欢迎继续讨论[比心心]

**Comment by stream2000** [comment]
谢谢建议~没什么后续讨论的话我先close了哈
